# SnakeLLM — somatic-variant-calling
# Somatic variant calling using GATK4 Mutect2 for paired tumor-normal samples following GATK best practices.

configfile: "config.yaml"
samples = config["samples"]

rule all:
    input:
        "qc/multiqc/multiqc_report.html",
        "qc/multiqc/multiqc_data",

rule fastqc_raw:
    input:
        r1 = "data/raw/{sample}_R1.fastq.gz",
        r2 = "data/raw/{sample}_R2.fastq.gz",
    output:
        "qc/fastqc/{sample}_R1_fastqc.html",
        "qc/fastqc/{sample}_R1_fastqc.zip",
        "qc/fastqc/{sample}_R2_fastqc.html",
        "qc/fastqc/{sample}_R2_fastqc.zip",
    params:
        outdir = "qc/fastqc",
        threads = 4,
    threads: 4
    resources:
        mem_mb  = 4000,
        runtime = 60
    log:
        "logs/fastqc/{sample}.log"
    shell:
        "fastqc --threads {params.threads} --outdir {params.outdir} {input[0]} {input[1]} 2> {log}"

rule trim_reads:
    input:
        r1 = "data/raw/{sample}_R1.fastq.gz",
        r2 = "data/raw/{sample}_R2.fastq.gz",
    output:
        "trimmed/{sample}_R1_paired.fastq.gz",
        "trimmed/{sample}_R1_unpaired.fastq.gz",
        "trimmed/{sample}_R2_paired.fastq.gz",
        "trimmed/{sample}_R2_unpaired.fastq.gz",
    params:
        adapters = "resources/adapters.fa",
        leading = 3,
        trailing = 3,
        slidingwindow = "4:15",
        minlen = 36,
        threads = 8,
    threads: 8
    resources:
        mem_mb  = 8000,
        runtime = 90
    log:
        "logs/trimmomatic/{sample}.log"
    shell:
        "trimmomatic PE -threads {params.threads} {input[0]} {input[1]} {output[0]} {output[1]} {output[2]} {output[3]} ILLUMINACLIP:{params.adapters}:2:30:10 LEADING:{params.leading} TRAILING:{params.trailing} SLIDINGWINDOW:{params.slidingwindow} MINLEN:{params.minlen} 2> {log}"

rule bwa_mem2_align:
    input:
        r1 = "trimmed/{sample}_R1_paired.fastq.gz",
        r2 = "trimmed/{sample}_R2_paired.fastq.gz",
    output:
        "aligned/{sample}.bam",
    params:
        ref = "resources/reference/genome.fa",
        threads = 16,
        read_group = "@RG\tID:{sample}\tSM:{sample}\tPL:ILLUMINA\tLB:{sample}",
    threads: 16
    resources:
        mem_mb  = 32000,
        runtime = 240
    log:
        "logs/bwa_mem2/{sample}.log"
    shell:
        "bwa-mem2 mem -t {params.threads} -R '{params.read_group}' {params.ref} {input[0]} {input[1]} | samtools view -bS - > {output[0]} 2> {log}"

rule samtools_sort_index:
    input:
        "aligned/{sample}.bam"
    output:
        "sorted/{sample}.sorted.bam",
        "sorted/{sample}.sorted.bam.bai",
    params:
        threads = 8,
    threads: 8
    resources:
        mem_mb  = 16000,
        runtime = 120
    log:
        "logs/samtools/{sample}.log"
    shell:
        "samtools sort -@ {params.threads} -o {output[0]} {input[0]} 2> {log[0]} && samtools index {output[0]} 2>> {log[0]} 2> {log}"

rule mark_duplicates:
    input:
        "sorted/{sample}.sorted.bam"
    output:
        "dedup/{sample}.dedup.bam",
        "dedup/{sample}.dedup.bam.bai",
        "dedup/{sample}.metrics.txt",
    params:
        java_opts = "-Xmx16g",
    threads: 4
    resources:
        mem_mb  = 20000,
        runtime = 120
    log:
        "logs/picard/{sample}.log"
    shell:
        "picard {params.java_opts} MarkDuplicates INPUT={input[0]} OUTPUT={output[0]} METRICS_FILE={output[2]} CREATE_INDEX=true VALIDATION_STRINGENCY=SILENT 2> {log}"

rule base_recalibrator:
    input:
        "dedup/{sample}.dedup.bam",
        "dedup/{sample}.dedup.bam.bai",
    output:
        "bqsr/{sample}.recal.table",
    params:
        ref = "resources/reference/genome.fa",
        known_sites_dbsnp = "resources/dbsnp.vcf.gz",
        known_sites_mills = "resources/mills_indels.vcf.gz",
        known_sites_1000g = "resources/1000g_indels.vcf.gz",
        java_opts = "-Xmx16g",
    threads: 4
    resources:
        mem_mb  = 20000,
        runtime = 180
    log:
        "logs/bqsr/base_recalibrator_{sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' BaseRecalibrator -I {input[0]} -R {params.ref} --known-sites {params.known_sites_dbsnp} --known-sites {params.known_sites_mills} --known-sites {params.known_sites_1000g} -O {output[0]} 2> {log}"

rule apply_bqsr:
    input:
        "dedup/{sample}.dedup.bam",
        "dedup/{sample}.dedup.bam.bai",
        "bqsr/{sample}.recal.table",
    output:
        "bqsr/{sample}.bqsr.bam",
        "bqsr/{sample}.bqsr.bam.bai",
    params:
        ref = "resources/reference/genome.fa",
        java_opts = "-Xmx16g",
    threads: 4
    resources:
        mem_mb  = 20000,
        runtime = 180
    log:
        "logs/bqsr/apply_bqsr_{sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' ApplyBQSR -I {input[0]} -R {params.ref} --bqsr-recal-file {input[2]} -O {output[0]} 2> {log}"

rule get_pileup_summaries:
    input:
        "bqsr/{sample}.bqsr.bam",
        "bqsr/{sample}.bqsr.bam.bai",
    output:
        "contamination/{sample}.pileup.table",
    params:
        ref = "resources/reference/genome.fa",
        germline_resource = "resources/small_exac_common.vcf.gz",
        java_opts = "-Xmx8g",
    threads: 4
    resources:
        mem_mb  = 12000,
        runtime = 120
    log:
        "logs/get_pileup_summaries/{sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' GetPileupSummaries -I {input[0]} -R {params.ref} -V {params.germline_resource} -L {params.germline_resource} -O {output[0]} 2> {log}"

rule mutect2:
    input:
        "bqsr/{tumor_sample}.bqsr.bam",
        "bqsr/{tumor_sample}.bqsr.bam.bai",
        "bqsr/{normal_sample}.bqsr.bam",
        "bqsr/{normal_sample}.bqsr.bam.bai",
    output:
        "mutect2/{tumor_sample}_vs_{normal_sample}.vcf.gz",
        "mutect2/{tumor_sample}_vs_{normal_sample}.vcf.gz.tbi",
        "mutect2/{tumor_sample}_vs_{normal_sample}.f1r2.tar.gz",
        "mutect2/{tumor_sample}_vs_{normal_sample}.stats",
    params:
        ref = "resources/reference/genome.fa",
        germline_resource = "resources/af-only-gnomad.vcf.gz",
        pon = "resources/panel_of_normals.vcf.gz",
        java_opts = "-Xmx16g",
        threads = 4,
    threads: 4
    resources:
        mem_mb  = 20000,
        runtime = 480
    log:
        "logs/mutect2/{tumor_sample}_vs_{normal_sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' Mutect2 -R {params.ref} -I {input[0]} -tumor {wildcards.tumor_sample} -I {input[2]} -normal {wildcards.normal_sample} --germline-resource {params.germline_resource} --panel-of-normals {params.pon} --f1r2-tar-gz {output[2]} -O {output[0]} 2> {log}"

rule calculate_contamination:
    input:
        "contamination/{tumor_sample}.pileup.table",
        "contamination/{normal_sample}.pileup.table",
    output:
        "contamination/{tumor_sample}_vs_{normal_sample}.contamination.table",
        "contamination/{tumor_sample}_vs_{normal_sample}.segmentation.table",
    params:
        java_opts = "-Xmx8g",
    threads: 2
    resources:
        mem_mb  = 10000,
        runtime = 60
    log:
        "logs/calculate_contamination/{tumor_sample}_vs_{normal_sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' CalculateContamination -I {input[0]} -matched {input[1]} --tumor-segmentation {output[1]} -O {output[0]} 2> {log}"

rule learn_read_orientation_model:
    input:
        "mutect2/{tumor_sample}_vs_{normal_sample}.f1r2.tar.gz"
    output:
        "mutect2/{tumor_sample}_vs_{normal_sample}.read_orientation_model.tar.gz",
    params:
        java_opts = "-Xmx8g",
    threads: 2
    resources:
        mem_mb  = 10000,
        runtime = 60
    log:
        "logs/learn_read_orientation/{tumor_sample}_vs_{normal_sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' LearnReadOrientationModel -I {input[0]} -O {output[0]} 2> {log}"

rule filter_mutect_calls:
    input:
        "mutect2/{tumor_sample}_vs_{normal_sample}.vcf.gz",
        "mutect2/{tumor_sample}_vs_{normal_sample}.vcf.gz.tbi",
        "mutect2/{tumor_sample}_vs_{normal_sample}.stats",
        "contamination/{tumor_sample}_vs_{normal_sample}.contamination.table",
        "contamination/{tumor_sample}_vs_{normal_sample}.segmentation.table",
        "mutect2/{tumor_sample}_vs_{normal_sample}.read_orientation_model.tar.gz",
    output:
        "filtered/{tumor_sample}_vs_{normal_sample}.filtered.vcf.gz",
        "filtered/{tumor_sample}_vs_{normal_sample}.filtered.vcf.gz.tbi",
    params:
        ref = "resources/reference/genome.fa",
        java_opts = "-Xmx8g",
    threads: 2
    resources:
        mem_mb  = 12000,
        runtime = 120
    log:
        "logs/filter_mutect_calls/{tumor_sample}_vs_{normal_sample}.log"
    shell:
        "gatk --java-options '{params.java_opts}' FilterMutectCalls -R {params.ref} -V {input[0]} --stats {input[2]} --contamination-table {input[3]} --tumor-segmentation {input[4]} --ob-priors {input[5]} -O {output[0]} 2> {log}"

rule vep_annotate:
    input:
        "filtered/{tumor_sample}_vs_{normal_sample}.filtered.vcf.gz"
    output:
        "annotated/{tumor_sample}_vs_{normal_sample}.annotated.vcf.gz",
        "annotated/{tumor_sample}_vs_{normal_sample}.annotated.vcf.gz.tbi",
        "annotated/{tumor_sample}_vs_{normal_sample}.vep_summary.html",
    params:
        vep_cache = "resources/vep_cache",
        species = "homo_sapiens",
        assembly = "GRCh38",
        threads = 4,
    threads: 4
    resources:
        mem_mb  = 16000,
        runtime = 180
    log:
        "logs/vep/{tumor_sample}_vs_{normal_sample}.log"
    shell:
        "vep --input_file {input[0]} --output_file {output[0]} --stats_file {output[2]} --vcf --compress_output bgzip --cache --dir_cache {params.vep_cache} --species {params.species} --assembly {params.assembly} --fork {params.threads} --everything --force_overwrite 2> {log[0]} && tabix -p vcf {output[0]} 2> {log}"

rule bcftools_stats:
    input:
        "annotated/{tumor_sample}_vs_{normal_sample}.annotated.vcf.gz"
    output:
        "qc/bcftools/{tumor_sample}_vs_{normal_sample}.stats.txt",
    threads: 2
    resources:
        mem_mb  = 4000,
        runtime = 30
    log:
        "logs/bcftools/{tumor_sample}_vs_{normal_sample}.log"
    shell:
        "bcftools stats {input[0]} > {output[0]} 2> {log}"

rule multiqc:
    input:
        ancient("qc/fastqc"),
        ancient("logs/trimmomatic"),
        ancient("dedup"),
        ancient("qc/bcftools"),
    output:
        "qc/multiqc/multiqc_report.html",
        "qc/multiqc/multiqc_data",
    params:
        outdir = "qc/multiqc",
        config = "resources/multiqc_config.yaml",
    threads: 2
    resources:
        mem_mb  = 8000,
        runtime = 30
    log:
        "logs/multiqc/multiqc.log"
    shell:
        "multiqc qc/fastqc logs/trimmomatic dedup qc/bcftools --outdir {params.outdir} --config {params.config} 2> {log}"